### ISSUE TITLE
Simulator tests aren't aligned with the current branch version

### ISSUE THREAD

**Issue by julienjpk** [Nolyurn/ApiMqtt#2]
The following errors occur when testing:

- **All tests** : the `add` method [expects a callback](https://github.com/Nolyurn/ApiMqtt/blob/59ecee9088c2db63090cce708537313f38cb426b/services/simulator/sensors/src/sensors.js#L88) parameter. A dummy function can be used (when `expectAddSensorError` isn't).
- *Type property is invalid* : this test uses a 0 frequency, which is invalid. The same happens in **all** *"sensor type errors"* tests.
- *Sensor name already used* : this test doesn't add twice, when it should. The second error expect therefore fails.

Commit c506acd updates error messages but does not fix these.

**Comment by julienjpk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pass all tests (awaiting tester review)](https://trello.com/c/yz0y6185/26-pass-all-tests-awaiting-tester-review)

**Comment by Alekshar** [comment]
"Sensor name already used : this test doesn't add twice, when it should. The second error expect therefore fails."
It does call add twice but the second call is through expectAddSensorError

others errors have been fixed
